# from dbinfo import*

Tashkent=[
{'id':1,'name':'National University of Uzbekistan'},
{'id':2,'name':'Tashkent University of Information Technologies'},
{'id':3,'name':'Tashkent State University of Economics'},
{'id':4,'name':'Tashkent State Technical University'},
{'id':5,'name':'University of World Economy and Diplomacy'},
{'id':6,'name':'Tashkent State Agrarian University'},
{'id':7,'name':'Westminster International University in Tashkent'},
{'id':8,'name':'Tashkent Institute of Railway Transport Engineers'},
{'id':9,'name':'Inha University in Tashkent'},
{'id':10,'name':'Tashkent State Institute of Oriental Studies'},
{'id':11,'name':'Tashkent State University of Law'},
{'id':12,'name':'Tashkent Institute of Irrigation and Agricultural Mechanization Engineers'},
{'id':13,'name':'Tashkent State Pedagogical University'},
{'id':14,'name':'Uzbek State University of World Languages'},
{'id':15,'name':'Tashkent Financial Institute'},
{'id':16,'name':'Tashkent Medical Academy'},
{'id':17,'name':'National Institute of Arts and Culture of Uzbekistan'},
{'id':18,'name':'State Conservatory of Uzbekistan'},
{'id':19,'name':'Tashkent Institute of Chemical Technology'},
{'id':20,'name':'Tashkent Pediatric Medical Institute'},
{'id':21,'name':'Turin Polytechnic University in Tashkent'},
{'id':22,'name':'Management Development Institute of Singapore in Tashkent'},
{'id':23,'name':'Tashkent Pharmaceutical Institute'},
{'id':24,'name':'Tashkent State University of Uzbek Language and Literature'},
{'id':25,'name':'Tashkent State Dental Institute'},
{'id':26,'name':'Tashkent Islamic University'},
{'id':27,'name':'Russian State University of Oil and Gas in Tashkent'},
{'id':28,'name':'Tashkent Institute of Textile and Light Industry'},
{'id':29,'name':'Tashkent Institute of Architecture and Construction'},
{'id':30,'name':'Banking and Finance Academy'},
{'id':31,'name':'National Institute of Fine Art and Design'},
{'id':32,'name':'Moscow State University in Tashkent'},
{'id':33,'name':'Russian University of Economics in Tashkent'},
{'id':34,'name':'Tashkent Automobile and Road Construction Institute'},
{'id':35,'name':'Tashkent State Higher School of National Dance and Choreography'},
{'id':36,'name':'Uzbek State Institute of Physical Culture'},
{'id':37,'name':'Tax Academy of the State Tax Committee of the Republic of Uzbekistan'}
]
Tashkent2=[
{'id':1,'as_id':1,'name':'Matematika'},
{'id':2,'as_id':1,'name':'Amaliy matematika va intellektual texnologiyalar'},
{'id':3,'as_id':1,'name':'Fizika'},
{'id':4,'as_id':1,'name':'Biologiya'},
{'id':5,'as_id':1,'name':'Ekologiya'},
{'id':6,'as_id':1,'name':'Kimyo'},
{'id':7,'as_id':1,'name':'Xorijiy filologiya'},
{'id':8,'as_id':1,'name':'Ijtimoiy fanlar'},
{'id':9,'as_id':1,'name':'Jurnalistika'},
{'id':10,'as_id':1,'name':'Tarix'},
{'id':11,'as_id':1,'name':'Geografiya va geoaxborot tizimlari'},
{'id':12,'as_id':1,'name':'Geologiya va muhandislik geologiyasi'},
{'id':13,'as_id':1,'name':'Gidrometeorologiya'},
{'id':14,'as_id':1,'name':"Taekvondo va sport mashg'ulotlari"},
{'id':15,'as_id':1,'name':"O'zbek filologiyasi"},
{'id':16,'as_id':2,'name':'Kompyuter muhandisligi'},
{'id':17,'as_id':2,'name':"Dasturiy ta'minot muhandisligi"},
{'id':18,'as_id':2,'name':'Kibercafsizlik'},
{'id':19,'as_id':2,'name':'Telekammunikatsiya texnalogiyalari'},
{'id':20,'as_id':2,'name':'televizion texnalogiyalar'},
{'id':21,'as_id':2,'name':'Radio va mobile aloqa'},
{'id':22,'as_id':2,'name':'AKT sohasida iqtisodiyot va menejment'},
{'id':23,'as_id':2,'name':"AKT sohasida kasbiy ta'lim"},
# {'id':24,'as_id':1,'name':'Matematika'},
{'id':25,'as_id':1,'name':'Amaliy matematika va intellektual texnologiyalar'},
{'id':26,'as_id':1,'name':'Fizika'},
{'id':27,'as_id':1,'name':'Biologiya'},
{'id':28,'as_id':1,'name':'Ekologiya'},
{'id':29,'as_id':1,'name':'Kimyo'},
{'id':30,'as_id':1,'name':'Xorijiy filologiya'},
{'id':31,'as_id':1,'name':'Ijtimoiy fanlar'},
{'id':32,'as_id':1,'name':'Jurnalistika'},
{'id':33,'as_id':1,'name':'Tarix'},
{'id':34,'as_id':1,'name':'Geografiya va geoaxborot tizimlari'},
{'id':35,'as_id':1,'name':'Geologiya va muhandislik geologiyasi'},
{'id':36,'as_id':1,'name':'Gidrometeorologiya'},
{'id':37,'as_id':1,'name':"Taekvondo va sport mashg'ulotlari"},
{'id':38,'as_id':1,'name':"O'zbek filologiyasi"},
{'id':39,'as_id':2,'name':'Kompyuter muhandisligi'},
{'id':40,'as_id':2,'name':"Dasturiy ta'minot muhandisligi"},
{'id':41,'as_id':2,'name':'Kibercafsizlik'},
{'id':42,'as_id':2,'name':'Telekammunikatsiya texnalogiyalari'},
{'id':43,'as_id':2,'name':'televizion texnalogiyalar'},
{'id':44,'as_id':2,'name':'Radio va mobile aloqa'},
{'id':45,'as_id':2,'name':'AKT sohasida iqtisodiyot va menejment'},
{'id':46,'as_id':2,'name':"AKT sohasida kasbiy ta'lim"},
]
